apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend-pod
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: frontend-pod
    spec:
      containers:
      - name: frontend
        env:
        - name: REACT_APP_BACKEND
          value: https://backend.gonboarding.com
        image: kwendim/gebeya:frontend
        ports:
        - containerPort: 80
        #imagePullPolicy: Always
        command: ["./docker-entrypoint.sh"]
      restartPolicy: Always      
--- 
apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
  name: frontend-service
spec:
  ports:
  - port: 8080
    targetPort: 80
  selector:
    app: frontend-pod
  type: ClusterIP
