apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: web-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    ingress.kubernetes.io/ssl-redirect: "true"
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  tls:
  - hosts:
    - webapp.gonboarding.com
    - webapp.gonboarding.com
    - webapp.gonboarding.com
    - webapp.gonboarding.com
    secretName: esp-tls
  rules:
    - host: backend.gonboarding.com
      http:
        paths:
          - path: /
            pathType: "Prefix"
            backend:
              serviceName: backend-service
              servicePort: 8080
    - host: keycloak.gonboarding.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: keycloak
              servicePort: 8080
    - host: webapp.gonboarding.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: frontend-service
              servicePort: 8080

    - host: jenkins.gonboarding.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              serviceName: cd-jenkins
              servicePort: 8080
